# Day 9 — NumPy Fundamentals
Use NumPy for fast numerical computing.

## 1. ndarray vs Python Lists

In [1]:
import numpy as np

python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)

print("List:", python_list, type(python_list))
print("Array:", numpy_array, type(numpy_array))
print("dtype:", numpy_array.dtype)

List: [1, 2, 3, 4, 5] <class 'list'>
Array: [1 2 3 4 5] <class 'numpy.ndarray'>
dtype: int64


## 2. dtypes & Shapes

In [2]:
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1.5, 2.5, 3.5], dtype=np.float64)

matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("int_array dtype:", int_array.dtype)
print("float_array dtype:", float_array.dtype)
print("matrix shape:", matrix.shape)
print("matrix ndim:", matrix.ndim)
print("matrix size:", matrix.size)

int_array dtype: int32
float_array dtype: float64
matrix shape: (2, 3)
matrix ndim: 2
matrix size: 6


## 3. Creating Arrays

In [3]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
range_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 5)
random_array = np.random.rand(3, 3)

print("zeros:\n", zeros)
print("ones:\n", ones)
print("arange:", range_array)
print("linspace:", linspace_array)
print("random:\n", random_array)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
random:
 [[0.54015587 0.69378473 0.47872879]
 [0.12431954 0.62268674 0.10768919]
 [0.02636158 0.82600162 0.96898485]]


## 4. Indexing, Slicing & Boolean Masks

In [4]:
grid = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Element at row 1, col 2:", grid[1, 2])
print("First two rows:\n", grid[:2])
print("Second column:", grid[:, 1])

mask = grid > 50
print("Boolean mask:\n", mask)
print("Values greater than 50:", grid[mask])

Element at row 1, col 2: 60
First two rows:
 [[10 20 30]
 [40 50 60]]
Second column: [20 50 80]
Boolean mask:
 [[False False False]
 [False False  True]
 [ True  True  True]]
Values greater than 50: [60 70 80 90]


## 5. Vectorized Operations & Broadcasting

In [5]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("Element-wise sum:", a + b)
print("Element-wise product:", a * b)

# Broadcasting: adding a scalar to every element without a loop
print("Broadcast add 5:", a + 5)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
row_vector = np.array([10, 20, 30])
print("Broadcast matrix + row vector:\n", matrix + row_vector)

Element-wise sum: [11 22 33]
Element-wise product: [10 40 90]
Broadcast add 5: [6 7 8]
Broadcast matrix + row vector:
 [[11 22 33]
 [14 25 36]]


## 6. Aggregations

In [6]:
data = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum (all):", data.sum())
print("Sum (axis=0, per column):", data.sum(axis=0))
print("Sum (axis=1, per row):", data.sum(axis=1))
print("Mean:", data.mean())
print("Std dev:", data.std())

Sum (all): 21
Sum (axis=0, per column): [5 7 9]
Sum (axis=1, per row): [ 6 15]
Mean: 3.5
Std dev: 1.707825127659933


## 7. Reshaping & Stacking

In [7]:
flat = np.arange(1, 7)
reshaped = flat.reshape(2, 3)

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Reshaped:\n", reshaped)
print("Vertical stack:\n", np.vstack([x, y]))
print("Horizontal stack:", np.hstack([x, y]))

Reshaped:
 [[1 2 3]
 [4 5 6]]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


## 8. Basic Linear Algebra

In [8]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Dot product:", np.dot(v1, v2))
print("Matrix multiplication:\n", matrix_a @ matrix_b)
print("Transpose:\n", matrix_a.T)

Dot product: 32
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose:
 [[1 3]
 [2 4]]


## 9. Hands-on: Vectorization Speed Comparison
Comparing a pure-Python loop against NumPy's vectorized operations on the same computation.

In [9]:
import time

size = 1_000_000
data = list(range(size))
numpy_data = np.arange(size)

# Pure Python loop
start = time.time()
squared_python = [x ** 2 for x in data]
python_time = time.time() - start

# NumPy vectorized
start = time.time()
squared_numpy = numpy_data ** 2
numpy_time = time.time() - start

print(f"Pure Python time: {python_time:.4f} seconds")
print(f"NumPy vectorized time: {numpy_time:.4f} seconds")
print(f"NumPy is {python_time / numpy_time:.1f}x faster")

Pure Python time: 0.0755 seconds
NumPy vectorized time: 0.0038 seconds
NumPy is 19.9x faster
